require([
  './charts.js',
  './navigation.js',
  './preferDarkMode.js', 
  './cards/clock.js',
  './cards/counter.js',
  './cards/dimmer.js',
  './cards/forecast.js',
  './cards/gauge.js',
  './cards/rgb-color-picker.js',
  './cards/switch.js',
  './cards/thermometer.js',
  './cards/weather.js',
  './Yadoms.js'
]);